File log = new File(basedir, 'build.log')
assert log.exists()
assert log.text.contains( 'GitHub22Bad.java:11: Undefined reference: boolean java.util.Optional.isPresent()' )
assert log.text.contains( 'GitHub22Bad.java:11: Undefined reference: java.util.function.Predicate' )
assert log.text.contains( 'GitHub22Bad.java:15: Undefined reference: boolean java.util.Optional.isPresent()' )
assert log.text.contains( 'GitHub22Bad.java:15: Undefined reference: java.util.function.Predicate' )
assert log.text.contains( 'GitHub22Bad.java:19: Undefined reference: java.util.function.Predicate' )
assert log.text.contains( 'GitHub22Bad.java:23: Undefined reference: java.util.function.Predicate' )
assert log.text.contains( 'GitHub22Bad.java:27: Undefined reference: java.util.function.Predicate' )
assert log.text.contains( 'GitHub22Bad.java:31: Undefined reference: boolean java.util.Optional.isPresent()' )
assert log.text.contains( 'GitHub22Bad.java:31: Undefined reference: java.util.function.Predicate' )
assert log.text.contains( 'GitHub22Bad.java:35: Undefined reference: java.util.function.Predicate' )
