File log = new File(basedir, 'build.log')
assert log.exists()
assert !log.text.contains( 'Issue41Bad.java: Undefined reference: ReflectiveOperationException' )
assert log.text.contains( 'Issue41Bad.java:15: Undefined reference: ReflectiveOperationException' )
assert !log.text.contains( 'Issue41Bad.java:19: Undefined reference: ReflectiveOperationException' )
assert log.text.contains( 'Issue41Bad.java:28: Undefined reference: ReflectiveOperationException' )
assert !log.text.contains( 'Issue41Bad.java:32: Undefined reference: ReflectiveOperationException' )
assert log.text.contains( 'Issue41Bad.java:44: Undefined reference: ReflectiveOperationException' )
assert log.text.contains( 'Issue41Bad.java:48: Undefined reference: ReflectiveOperationException' )
