name: Release Drafter
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
    steps:
      - uses: release-drafter/release-drafter@00ce30b0ce8a4d67bccfca59421cdf6c55dd0784 # v6.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
